### ISSUE TITLE
Unknown POSIX error while trying to render a template

### ISSUE THREAD

**Issue by thiagomajesk** [handlecommerce/liquex#42]
Hi! I'm trying to render a liquid template using the provided information on the README and I'm getting this error. 

Layout.liquid

```liquid
{% render "post" %}
```

Post.liquid
```liquid
Hello From Post
```

And then:

```elixir
content = File.read!("theme/layout.liquid")
{:ok, template_ast} = Liquex.parse(content)
{content, _context} = Liquex.render!(template_ast, %{})
```

```
** (File.Error) could not  nil: unknown POSIX error
    (liquex 0.10.1) lib/liquex/file_system.ex:22: Liquex.FileSystem.Liquex.BlankFileSystem.read_template_file/2
    (liquex 0.10.1) lib/liquex/tag/render_tag.ex:218: anonymous fn/2 in Liquex.Tag.RenderTag.load_contents/2
    (liquex 0.10.1) lib/liquex/tag/render_tag.ex:143: Liquex.Tag.RenderTag.render/2
    (liquex 0.10.1) lib/liquex/render.ex:25: Liquex.Render.render!/3
    (liquex 0.10.1) lib/liquex.ex:213: Liquex.render!/2
    iex:7: (file)
```

Do I have to do any other setup for this to work?

**Comment by markglenn** [comment]
I apologize for not responding earlier, but this is happening because you haven't set a file system for your context. See the example below. I have fixed the error to instead show an error message to help avoid this issue in the future:

```elixir
file_system = Liquex.LocalFileSystem.new("/some/path")

# Whatever your scope is
scope = %{}

context = Liquex.Context.new(scope, file_system: file_system)
Liquex.render!(template, context)
```
